---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routes
spec:
  project: ambassador
  source:
    repoURL: https://github.com/alajfit/k8s.gitops-setup.git
    path: routes
  destination:
    server: https://kubernetes.default.svc
    namespace: ambassador
